# This is a basic workflow to help you get started with Actions

name: CI

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: "ubuntu-latest"
    container: "blang/latex:ubuntu"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      
      - name: Run a one-line script
        run: "latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=. Bologna_CV.tex"

      - name: Upload CV
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: Bologna_CV.pdf
